baseurl = "https://hochia.github.io/r-statistics/"
languageCode = "en-us"
title = "Hochia learning R"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji = true
hasCJKLanguage = true
copyright = "&copy; 2019. All rights reserved."

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/hochia"
# [[menu.main]]
#    name = "Notice"
#    url = "/notice/"
# put .html file directly in \static

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "python"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    
    # googleAnalytics = "Google Analytics tracking ID"
    # disqus = "Disqus shortname"

    # path to the favicon, under "static"
    favicon = "logo.png"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

